config:
  environments_root: ~/.spack/environments
  install_tree:
    root: ~/privatemodules/bin
    projections:
      all: "{architecture}/{compiler.name}-{compiler.version}/{name}-{version}"
  template_dirs:
    - ~/privatemodules/templates
  license_dir: ~/privatemodules/licenses
  build_stage:
    - $tempdir/$user/spack-stage
    - $user_cache_path/stage
  test_stage: $user_cache_path/test
  source_cache: $user_cache_path/source
  misc_cache: $user_cache_path/cache
