config:
  build_jobs: 16
  concurrent_packages: 16
  install_tree:
    root: $CHAPAR_HOME_ROOT/store
    projections:
      all: "{architecture}/{compiler.name}-{compiler.version}/{name}-{version}"
  template_dirs:
    - $CHAPAR_HOME_ROOT/templates
  license_dir: $CHAPAR_HOME_ROOT/licenses
  build_stage:
    - $tempdir/$user/spack-stage
    - $user_cache_path/stage
  test_stage: $user_cache_path/test
  source_cache: $user_cache_path/source
  misc_cache: $user_cache_path/cache
